version: '3.7'
services:
  redismod:
    image: redislabs/redismod
    container_name: redismod
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-insight
    ports:
      - 8001:8001
  api:
    build:
      context: ./api/
    container_name: api
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - redismod
    command: npm run start:watch
    environment:
      - REDIS:redismod
    ports:
      - 3001:3001
  bidding-service:
    build:
      context: ./bidding-service/
    container_name: bidding-service
    volumes:
      - ./bidding-service/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - redismod
    command: npm run start:watch
    environment:
      - REDIS:redismod
    ports:
      - 3002:3002
  client:
    build:
      context: ./client/
    container_name: client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - api
    ports:
      - 3000:3000

volumes:
  redis-data: